package com.lds.vo;
// Generated 28 aout 2012 18:10:32 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private String idarticle;
     private String descarticle;
     private Integer qntarticle;
     private String marque;
     private String refcommerciale;
     private String refcommande;
     private String unite;
     private String categorie;
     private Set detailssortiearticles = new HashSet(0);
     private Set detailsbcarticles = new HashSet(0);
     private Set detailsbrarticles = new HashSet(0);
     private Set detailsdemandearticles = new HashSet(0);

    public Article() {
    }

	
    public Article(String idarticle) {
        this.idarticle = idarticle;
    }
    public Article(String idarticle, String descarticle, Integer qntarticle, String marque, String refcommerciale, String refcommande, String unite, String categorie, Set detailssortiearticles, Set detailsbcarticles, Set detailsbrarticles, Set detailsdemandearticles) {
       this.idarticle = idarticle;
       this.descarticle = descarticle;
       this.qntarticle = qntarticle;
       this.marque = marque;
       this.refcommerciale = refcommerciale;
       this.refcommande = refcommande;
       this.unite = unite;
       this.categorie = categorie;
       this.detailssortiearticles = detailssortiearticles;
       this.detailsbcarticles = detailsbcarticles;
       this.detailsbrarticles = detailsbrarticles;
       this.detailsdemandearticles = detailsdemandearticles;
    }
   
    public String getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(String idarticle) {
        this.idarticle = idarticle;
    }
    public String getDescarticle() {
        return this.descarticle;
    }
    
    public void setDescarticle(String descarticle) {
        this.descarticle = descarticle;
    }
    public Integer getQntarticle() {
        return this.qntarticle;
    }
    
    public void setQntarticle(Integer qntarticle) {
        this.qntarticle = qntarticle;
    }
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }
    public String getRefcommerciale() {
        return this.refcommerciale;
    }
    
    public void setRefcommerciale(String refcommerciale) {
        this.refcommerciale = refcommerciale;
    }
    public String getRefcommande() {
        return this.refcommande;
    }
    
    public void setRefcommande(String refcommande) {
        this.refcommande = refcommande;
    }
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public Set getDetailssortiearticles() {
        return this.detailssortiearticles;
    }
    
    public void setDetailssortiearticles(Set detailssortiearticles) {
        this.detailssortiearticles = detailssortiearticles;
    }
    public Set getDetailsbcarticles() {
        return this.detailsbcarticles;
    }
    
    public void setDetailsbcarticles(Set detailsbcarticles) {
        this.detailsbcarticles = detailsbcarticles;
    }
    public Set getDetailsbrarticles() {
        return this.detailsbrarticles;
    }
    
    public void setDetailsbrarticles(Set detailsbrarticles) {
        this.detailsbrarticles = detailsbrarticles;
    }
    public Set getDetailsdemandearticles() {
        return this.detailsdemandearticles;
    }
    
    public void setDetailsdemandearticles(Set detailsdemandearticles) {
        this.detailsdemandearticles = detailsdemandearticles;
    }




}


