package com.lds.vo;
// Generated 28 aout 2012 17:26:50 by Hibernate Tools 3.2.1.GA



/**
 * DetailsbrfournitureId generated by hbm2java
 */
public class DetailsbrfournitureId  implements java.io.Serializable {


     private String numfourniture;
     private String numreception;

    public DetailsbrfournitureId() {
    }

    public DetailsbrfournitureId(String numfourniture, String numreception) {
       this.numfourniture = numfourniture;
       this.numreception = numreception;
    }
   
    public String getNumfourniture() {
        return this.numfourniture;
    }
    
    public void setNumfourniture(String numfourniture) {
        this.numfourniture = numfourniture;
    }
    public String getNumreception() {
        return this.numreception;
    }
    
    public void setNumreception(String numreception) {
        this.numreception = numreception;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsbrfournitureId) ) return false;
		 DetailsbrfournitureId castOther = ( DetailsbrfournitureId ) other; 
         
		 return ( (this.getNumfourniture()==castOther.getNumfourniture()) || ( this.getNumfourniture()!=null && castOther.getNumfourniture()!=null && this.getNumfourniture().equals(castOther.getNumfourniture()) ) )
 && ( (this.getNumreception()==castOther.getNumreception()) || ( this.getNumreception()!=null && castOther.getNumreception()!=null && this.getNumreception().equals(castOther.getNumreception()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumfourniture() == null ? 0 : this.getNumfourniture().hashCode() );
         result = 37 * result + ( getNumreception() == null ? 0 : this.getNumreception().hashCode() );
         return result;
   }   


}


