package com.lds.vo;
// Generated 28 aout 2012 18:10:32 by Hibernate Tools 3.2.1.GA



/**
 * Detailsarticlbesoin generated by hbm2java
 */
public class Detailsarticlbesoin  implements java.io.Serializable {


     private DetailsarticlbesoinId id;
     private Integer qntbesoin;
     private String nom_article;
     private Integer qntarticle;

    public Detailsarticlbesoin() {
    }

	
    public Detailsarticlbesoin(DetailsarticlbesoinId id) {
        this.id = id;
    }
    public Detailsarticlbesoin(DetailsarticlbesoinId id, Integer qntbesoin) {
       this.id = id;
       this.qntbesoin = qntbesoin;
    }
   
    public Detailsarticlbesoin(DetailsarticlbesoinId id, Integer qntbesoin, String nom_article) {
       this.id = id;
       this.qntbesoin = qntbesoin;
       this.nom_article=nom_article;
    }
    public DetailsarticlbesoinId getId() {
        return this.id;
    }
    
    public void setId(DetailsarticlbesoinId id) {
        this.id = id;
    }
    public Integer getQntbesoin() {
        return this.qntbesoin;
    }
    
    public void setQntbesoin(Integer qntbesoin) {
        this.qntbesoin = qntbesoin;
    }

    public String getNom_article() {
        return nom_article;
    }

    public void setNom_article(String nom_article) {
        this.nom_article = nom_article;
    }

    public Integer getQntarticle() {
        return qntarticle;
    }

    public void setQntarticle(Integer qntarticle) {
        this.qntarticle = qntarticle;
    }

 




}


