package com.lds.vo;
// Generated 28 aout 2012 17:26:50 by Hibernate Tools 3.2.1.GA



/**
 * Detailsbrfourniture generated by hbm2java
 */
public class Detailsbrfourniture  implements java.io.Serializable {


     private DetailsbrfournitureId id;
     private Fourniture fourniture;
     private Bonreception bonreception;
     private Integer qntlivre;

    public Detailsbrfourniture() {
    }

	
    public Detailsbrfourniture(DetailsbrfournitureId id, Fourniture fourniture, Bonreception bonreception) {
        this.id = id;
        this.fourniture = fourniture;
        this.bonreception = bonreception;
    }
    public Detailsbrfourniture(DetailsbrfournitureId id, Fourniture fourniture, Bonreception bonreception, Integer qntlivre) {
       this.id = id;
       this.fourniture = fourniture;
       this.bonreception = bonreception;
       this.qntlivre = qntlivre;
    }
   
    public DetailsbrfournitureId getId() {
        return this.id;
    }
    
    public void setId(DetailsbrfournitureId id) {
        this.id = id;
    }
    public Fourniture getFourniture() {
        return this.fourniture;
    }
    
    public void setFourniture(Fourniture fourniture) {
        this.fourniture = fourniture;
    }
    public Bonreception getBonreception() {
        return this.bonreception;
    }
    
    public void setBonreception(Bonreception bonreception) {
        this.bonreception = bonreception;
    }
    public Integer getQntlivre() {
        return this.qntlivre;
    }
    
    public void setQntlivre(Integer qntlivre) {
        this.qntlivre = qntlivre;
    }




}


