package com.lds.vo;
// Generated 28 aout 2012 18:10:32 by Hibernate Tools 3.2.1.GA



/**
 * Detailsbcfourniture generated by hbm2java
 */
public class Detailsbcfourniture  implements java.io.Serializable {


     private DetailsbcfournitureId id;
     private Double prixunitaire;
     private Integer qntcommande;
     private Integer qntlivre;

    public Detailsbcfourniture() {
    }

	
    public Detailsbcfourniture(DetailsbcfournitureId id) {
        this.id = id;
    }
    public Detailsbcfourniture(DetailsbcfournitureId id, Double prixunitaire, Integer qntcommande, Integer qntlivre) {
       this.id = id;
       this.prixunitaire = prixunitaire;
       this.qntcommande = qntcommande;
       this.qntlivre = qntlivre;
    }
   
    public DetailsbcfournitureId getId() {
        return this.id;
    }
    
    public void setId(DetailsbcfournitureId id) {
        this.id = id;
    }
    public Double getPrixunitaire() {
        return this.prixunitaire;
    }
    
    public void setPrixunitaire(Double prixunitaire) {
        this.prixunitaire = prixunitaire;
    }
    public Integer getQntcommande() {
        return this.qntcommande;
    }
    
    public void setQntcommande(Integer qntcommande) {
        this.qntcommande = qntcommande;
    }
    public Integer getQntlivre() {
        return this.qntlivre;
    }
    
    public void setQntlivre(Integer qntlivre) {
        this.qntlivre = qntlivre;
    }




}


