package com.lds.vo;
// Generated 28 aout 2012 18:10:32 by Hibernate Tools 3.2.1.GA



/**
 * Detailsbrarticle generated by hbm2java
 */
public class Detailsbrarticle  implements java.io.Serializable {


     private DetailsbrarticleId id;
     private Bonreception bonreception;
     private Article article;
     private Integer qntlivre;
     private Integer total_qntlivre;
     private Integer qnt_commander;


    public Detailsbrarticle() {
    }

	
    public Detailsbrarticle(DetailsbrarticleId id, Bonreception bonreception, Article article) {
        this.id = id;
        this.bonreception = bonreception;
        this.article = article;
    }
    public Detailsbrarticle(DetailsbrarticleId id, Bonreception bonreception, Article article, Integer qntlivre) {
       this.id = id;
       this.bonreception = bonreception;
       this.article = article;
       this.qntlivre = qntlivre;
    }
   
    public DetailsbrarticleId getId() {
        return this.id;
    }
    
    public void setId(DetailsbrarticleId id) {
        this.id = id;
    }
    
    public Integer getQnt_commander() {
        return qnt_commander;
    }

    public void setQnt_commander(Integer qnt_commander) {
        this.qnt_commander = qnt_commander;
    }

    public Integer getTotal_qntlivre() {
        return total_qntlivre;
    }

    public void setTotal_qntlivre(Integer total_qntlivre) {
        this.total_qntlivre = total_qntlivre;
    }
    

    public Bonreception getBonreception() {
        return this.bonreception;
    }
    
    public void setBonreception(Bonreception bonreception) {
        this.bonreception = bonreception;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Integer getQntlivre() {
        return this.qntlivre;
    }
    
    public void setQntlivre(Integer qntlivre) {
        this.qntlivre = qntlivre;
    }




}


