package com.lds.vo;
// Generated 28 aout 2012 18:10:32 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projet generated by hbm2java
 */
public class Projet  implements java.io.Serializable {


     private String idprojet;
     private Client client;
     private Date datedebutaffaire;     
     private String descprojet;     
     private Date dateintervention;
     private String lieuintervention;
     private String typeprojet;
     private String numdevis;
     private Date datedevis;
     private BigDecimal montantdevis;
     private String liendevis;     
     private String numfacture;
     private Date datefacture;
     private BigDecimal montantfacture;
     private String lienfacture;
     private Set boncommandes = new HashSet(0);
     private Set taches = new HashSet(0);

    public Projet() {
    }

	
    public Projet(String idprojet, Client client) {
        this.idprojet = idprojet;
        this.client = client;
    }
    public Projet(String idprojet, Client client, Date datedebutaffaire, String descprojet,Date dateintervention, String lieuintervention, String typeprojet, String numdevis,Date datedevis,BigDecimal montantdevis,String liendevis,String numfacture,Date datefacture,BigDecimal montantfacture,String lienfacture, Set boncommandes, Set taches) {
       this.idprojet = idprojet;
       this.client = client;
       this.datedebutaffaire = datedebutaffaire;       
       this.descprojet = descprojet;       
       this.dateintervention = dateintervention;
       this.lieuintervention = lieuintervention;
       this.typeprojet = typeprojet;      
       this.numdevis = numdevis;
       this.datedevis = datedevis;
       this.montantdevis = montantdevis;
       this.liendevis = liendevis;
       this.numfacture = numfacture;
       this.datefacture = datefacture;
       this.montantfacture = montantfacture;
       this.lienfacture = lienfacture;
       this.boncommandes = boncommandes;
       this.taches = taches;
    }
   
    public String getIdprojet() {
        return this.idprojet;
    }
    
    public void setIdprojet(String idprojet) {
        this.idprojet = idprojet;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDatedebutaffaire() {
        return this.datedebutaffaire;
    }
    
    public void setDatedebutaffaire(Date datedebutaffaire) {
        this.datedebutaffaire = datedebutaffaire;
    }

    public String getDescprojet() {
        return this.descprojet;
    }
    
    public void setDescprojet(String descprojet) {
        this.descprojet = descprojet;
    }
      
    public Date getDateintervention() {
        return this.dateintervention;
    }
    
    public void setDateintervention(Date dateintervention) {
        this.dateintervention = dateintervention;
    }
    public String getLieuintervention() {
        return this.lieuintervention;
    }
    
    public void setLieuintervention(String lieuintervention) {
        this.lieuintervention = lieuintervention;
    }
    public String getTypeprojet() {
        return this.typeprojet;
    }
    
    public void setTypeprojet(String typeprojet) {
        this.typeprojet = typeprojet;
    }

    public Date getDatedevis() {
        return datedevis;
    }

    public void setDatedevis(Date datedevis) {
        this.datedevis = datedevis;
    }

    public Date getDatefacture() {
        return datefacture;
    }

    public void setDatefacture(Date datefacture) {
        this.datefacture = datefacture;
    }

    public String getLiendevis() {
        return liendevis;
    }

    public void setLiendevis(String liendevis) {
        this.liendevis = liendevis;
    }

    public String getLienfacture() {
        return lienfacture;
    }

    public void setLienfacture(String lienfacture) {
        this.lienfacture = lienfacture;
    }

    public BigDecimal getMontantdevis() {
        return montantdevis;
    }

    public void setMontantdevis(BigDecimal montantdevis) {
        this.montantdevis = montantdevis;
    }

    public BigDecimal getMontantfacture() {
        return montantfacture;
    }

    public void setMontantfacture(BigDecimal montantfacture) {
        this.montantfacture = montantfacture;
    }

    public String getNumdevis() {
        return numdevis;
    }

    public void setNumdevis(String numdevis) {
        this.numdevis = numdevis;
    }

    public String getNumfacture() {
        return numfacture;
    }

    public void setNumfacture(String numfacture) {
        this.numfacture = numfacture;
    }

  
    
  
    public Set getBoncommandes() {
        return this.boncommandes;
    }
    
    public void setBoncommandes(Set boncommandes) {
        this.boncommandes = boncommandes;
    }
    public Set getTaches() {
        return this.taches;
    }
    
    public void setTaches(Set taches) {
        this.taches = taches;
    }

    public boolean equals(Object object) {
        return (object instanceof Projet) && (idprojet != null) 
             ? idprojet.equals(((Projet) object).idprojet) 
             : (object == this);
    }


}


