package com.lds.vo;
// Generated 28 aout 2012 18:10:32 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tache generated by hbm2java
 */
public class Tache  implements java.io.Serializable {


     private String numtache;
     private Projet projet;
     private String designationtache;
     private Integer durefabrication;
     private String lienimplementation;
     private String lienschema;
     private String lieutache;
     private String typetache;
     private Set bonsorties = new HashSet(0);
     private Set soustaches = new HashSet(0);
     private Set besoins = new HashSet(0);
     private Set detailstachepersonnels = new HashSet(0);

    public Tache() {
    }

	
    public Tache(String numtache, Projet projet) {
        this.numtache = numtache;
        this.projet = projet;
    }
    public Tache(String numtache, Projet projet, String designationtache, Integer durefabrication, String lienimplementation, String lienschema, String lieutache, String typetache, Set bonsorties, Set soustaches, Set besoins, Set detailstachepersonnels) {
       this.numtache = numtache;
       this.projet = projet;
       this.designationtache = designationtache;
       this.durefabrication = durefabrication;
       this.lienimplementation = lienimplementation;
       this.lienschema = lienschema;
       this.lieutache = lieutache;
       this.typetache = typetache;
       this.bonsorties = bonsorties;
       this.soustaches = soustaches;
       this.besoins = besoins;
       this.detailstachepersonnels = detailstachepersonnels;
    }
   
    public String getNumtache() {
        return this.numtache;
    }
    
    public void setNumtache(String numtache) {
        this.numtache = numtache;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public String getDesignationtache() {
        return this.designationtache;
    }
    
    public void setDesignationtache(String designationtache) {
        this.designationtache = designationtache;
    }
    public Integer getDurefabrication() {
        return this.durefabrication;
    }
    
    public void setDurefabrication(Integer durefabrication) {
        this.durefabrication = durefabrication;
    }
    public String getLienimplementation() {
        return this.lienimplementation;
    }
    
    public void setLienimplementation(String lienimplementation) {
        this.lienimplementation = lienimplementation;
    }
    public String getLienschema() {
        return this.lienschema;
    }
    
    public void setLienschema(String lienschema) {
        this.lienschema = lienschema;
    }
    public String getLieutache() {
        return this.lieutache;
    }
    
    public void setLieutache(String lieutache) {
        this.lieutache = lieutache;
    }
    public String getTypetache() {
        return this.typetache;
    }
    
    public void setTypetache(String typetache) {
        this.typetache = typetache;
    }
    public Set getBonsorties() {
        return this.bonsorties;
    }
    
    public void setBonsorties(Set bonsorties) {
        this.bonsorties = bonsorties;
    }
    public Set getSoustaches() {
        return this.soustaches;
    }
    
    public void setSoustaches(Set soustaches) {
        this.soustaches = soustaches;
    }
    public Set getBesoins() {
        return this.besoins;
    }
    
    public void setBesoins(Set besoins) {
        this.besoins = besoins;
    }
    public Set getDetailstachepersonnels() {
        return this.detailstachepersonnels;
    }
    
    public void setDetailstachepersonnels(Set detailstachepersonnels) {
        this.detailstachepersonnels = detailstachepersonnels;
    }




}


